name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # Please use a bot account/company account for commercial/industrial projects.
      - name: Set Git user
        run: |
          git config --global user.email "hoipang1e06@gmail.com"
          git config --global user.name "HoiPang2"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          CI: true

      - name: Cleanup
        run: rm -rf node_modules build
